---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hc-nginx-phpfpm

spec:
  replicas: 1
  minReadySeconds: 15
  template:
      metadata:
          labels:
              app: phpapp
      spec:
          containers:
          - image: <image-name>:latest
            imagePullPolicy: Always
            name: nginx
            ports:
                - containerPort: 80

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-db

spec:
  replicas: 1
  template:
      metadata:
          labels:
              app: mysqldb
      spec:
          containers:
          - image: mysql:5.6
            name: mysql
            env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mypassword"
            ports: 
                - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
      app: mysqldb
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
      app: phpapp
